name: restoranow_mobile
description: "RestoraNow mobile app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  file_picker: ^10.2.0
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
